nginx:
  build: ./nginx
  ports:
    - 80:80
    - 443:443
  links:
    - php56
  volumes_from:
    - code
  volumes:
    - ./nginx/sites:/etc/nginx/sites-enabled
    - ./nginx/logs:/var/log/nginx:rw
  restart: always

mailhog:
  image: mailhog/mailhog
  expose:
    - "1025"
    - "8025"
  ports:
    - "8025:8025"

mysql56:
  build: ./mysql56
  ports:
      - 3306:3306
  environment:
      MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - code
  volumes:
  - ./mysql56/data:/var/lib/mysql/:rw

php56:
  build: ./php56
  ports:
    - 9000:9000
  volumes_from:
    - code
  links:
    - mysql56:db
    - mailhog:mail
  environment:
    TERM: xterm

code:
  build: ./code
  volumes:
    - ./../../projects:/var/www/projects
  tty: true
